/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MailRequestDto } from '../../models/mail-request-dto';
import { MailResponseDto } from '../../models/mail-response-dto';

export interface SendMail$Params {
      body: MailRequestDto
}

export function sendMail(http: HttpClient, rootUrl: string, params: SendMail$Params, context?: HttpContext): Observable<StrictHttpResponse<MailResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sendMail.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MailResponseDto>;
    })
  );
}

sendMail.PATH = '/api/mail/send';
