/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileAttachmentDto } from '../models/file-attachment-dto';
export interface MailRequestDto {
  additionalData?: {
[key: string]: any;
};
  appCode: string;
  attachments?: Array<FileAttachmentDto>;
  company?: string;
  email: string;
  mailType: string;
  message: string;
  name: string;
  phone?: string;
  recaptchaToken?: string;
  subject?: string;
  website?: string;
}
