/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { SendMail$Params as SendMail$Params } from './fn/mail-controller/send-mail';
export { sendMail as sendMail } from './fn/mail-controller/send-mail';
export type { Health$Params as Health$Params } from './fn/mail-controller/health';
export { health as health } from './fn/mail-controller/health';
