/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { health } from '../fn/mail-controller/health';
import { Health$Params } from '../fn/mail-controller/health';
import { MailResponseDto } from '../models/mail-response-dto';
import { sendMail } from '../fn/mail-controller/send-mail';
import { SendMail$Params } from '../fn/mail-controller/send-mail';

@Injectable({ providedIn: 'root' })
export class MailControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `sendMail()` */
  static readonly SendMailPath = '/api/mail/send';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendMail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendMail$Response(params: SendMail$Params, context?: HttpContext): Promise<StrictHttpResponse<MailResponseDto>> {
    const obs = sendMail(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendMail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendMail(params: SendMail$Params, context?: HttpContext): Promise<MailResponseDto> {
    const resp = this.sendMail$Response(params, context);
    return resp.then((r: StrictHttpResponse<MailResponseDto>): MailResponseDto => r.body);
  }

  /** Path part for operation `health()` */
  static readonly HealthPath = '/api/mail/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `health()` instead.
   *
   * This method doesn't expect any request body.
   */
  health$Response(params?: Health$Params, context?: HttpContext): Promise<StrictHttpResponse<string>> {
    const obs = health(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `health$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  health(params?: Health$Params, context?: HttpContext): Promise<string> {
    const resp = this.health$Response(params, context);
    return resp.then((r: StrictHttpResponse<string>): string => r.body);
  }

}
