/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { FileAttachmentDto } from './models/file-attachment-dto';
export type { MailRequestDto } from './models/mail-request-dto';
export type { MailResponseDto } from './models/mail-response-dto';
